version: '2.0'

services:
#  zookeeper:
#    image: confluentinc/cp-zookeeper:latest
#    environment:
#      ZOOKEEPER_CLIENT_PORT: 2181
#    restart: always
#    network_mode: host
#  broker-kafka:
#    image: confluentinc/cp-kafka:latest
#    depends_on:
#      - zookeeper
#    ports:
#      - 9092:9092
#    environment:
#      KAFKA_BROKER_ID: 1
#      KAFKA_ZOOKEEPER_CONNECT: localhost:2181
#      KAFKA_LISTENERS: LISTENER_DOCKER://localhost:19092,LISTENER_HOST://0.0.0.0:9092
#      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER://localhost:19092,LISTENER_HOST://:9092
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER:PLAINTEXT,LISTENER_HOST:PLAINTEXT
#      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER
#      KAFKA_LOG_RETENTION_MINUTES: 1
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#      KAFKA_CREATE_TOPICS: "main_broker:1:1,processor:1:1,features_maker:1:1,saver:1:1,experiment_manager:1:1"
#    restart: always
#    network_mode: host
  topic_handlers:
#    depends_on:
#      - broker-kafka
    env_file:
      - docker/.env
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: always
    network_mode: host
